name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}

api-version: 1.13

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
  #- org.jsoup:jsoup:1.14.3
  #- com.zaxxer:HikariCP:5.0.1

softdepend: [AuthMe, BanManager, BungeeChatAPI, CMI, DiscordSRV, Factions, Feudal, ItemsAdder, Essentials, LegacyFactions, Lands, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, mcMMO, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, Vault, WorldEdit]
commands:  