name: PlayerModification
version: '${project.version}'
main: com.stand.PlayerModification
authors: [ MrDefault ]
description: The plugin which allows you to modify player's values per-world.
permissions:
  PlayerModification.access:
    default: op
  PlayerModification.PvpBypass:
    default: false
  PlayerModification.autoreset:
    default: false
commands:
  playermodification:
    usage: /<command>
    aliases: [pm, pmd]
    description: Usage of Player modfication plugin.
  pmadmin:
    usage: /<command>
    aliases: [pma]
    description: Admin command for Player modification plugin.
